version: '3.1'

services:
  redmine:
    container_name: redmine
    image: redmine:5.0.2
    restart: always
    ports:
      - 3000:3000/tcp 
    env_file:
      - .env
    volumes:
      - ./data/redmine:/usr/src/redmine/files
      
  # Hostname of container is the same as the name of the service.
  postgres:
    container_name: postgres
    image: postgres:14.4
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
